name: liquid_glass_renderer_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flex_color_picker: ^3.7.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  liquid_glass_renderer:
    path: ../
  heroine: ^0.5.0-dev.3
  rivership: ^0.3.0-dev.3
  smooth_sheets: ^0.12.0
  springster: ^1.0.0-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/