name: apple_liquid_glass
description: Liquid Glass Implementation according to Apple's Guidelines
version: 0.1.0-dev.8

homepage: https://whynotmake.it
repository: https://github.com/whynotmake-it/flutter_liquid_glass/tree/main/packages/apple_liquid_glass

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  liquid_glass_renderer: ^0.1.1-dev.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.1.1
  mocktail: ^1.0.3
